### PR TITLE
Refactor several methods, Add Support for custom views

### PR DESCRIPTION
**Pull request by faustbrian**

### CODE REVIEW

**Comment by faustbrian** [comment]
The constant StyleCI merges seem to have caused a conflict.

**Comment by ConsoleTVs** [comment]
This branch has conflicts that must be resolved

**Comment by ConsoleTVs** [comment]
I also made a commit

**Comment by faustbrian** [comment]
I also removed the 3.0 Facade info as there is no 3.0 yet and it is pointless to inform people about it yet as things might change.

**Comment by ConsoleTVs** [comment]
You added the wrong docs for the current version. People read the docs in the .md, regardless of the version, so thsi is wrong as for the current version:

```php
 'Charts' => ConsoleTVs\Charts\Facades\Charts::class, 
```

**Comment by faustbrian** [comment]
Fixed.

**Comment by ConsoleTVs** [comment]
Merged!

**Comment by faustbrian** [comment]
Thanks, 50% done with the Blade Templates. That's quite a bit of work.

**Comment by ConsoleTVs** [comment]
Yeah, I must imagine! I'm up for working again, gonna wait your commit to see how you create those templates and then I'm gonna try to implement something else haha :D

**Comment by faustbrian** [comment]
You can take a look here at the first few changes https://github.com/faustbrian/Charts/commit/ff2dc161f3554c064a85538f4c92fc5f1871bc87

Mostly have been replacing loops and conditionals and added partials to DRY the templates. Still a lot of stuff todo but it comes its way.

**Pull request merged**
