### PR TITLE
View Improvements - Part 2

### PR DESCRIPTION
**Pull request by faustbrian**
I fixed a few things like loop, conditionals and indentation in this PR.

There are still some loops and conditionals left to fix and some other issues that have been introduced by changes from other people lately.

I will be sending the last PR during this weekend and then we should test every chart available to see if there are any issues with the templates.

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
I agree! After that we can release the new version :D

**Comment by faustbrian** [comment]
After my next PR all changes that I are planned will be done, took a bit longer because of my job. Then it is just about testing every single chart to see if everything is working as intended which shouldn't take to long.

**Comment by ConsoleTVs** [comment]
Indeed, that's no hurry!

**Comment by ConsoleTVs** [comment]
Any news on any upcomming PR or I can start testing / creating 3.0

**Comment by faustbrian** [comment]
Will be ready tomorrow noon/evening, work kept me back a bit.

**Comment by ConsoleTVs** [comment]
Yes sure! I am looking forward adding new features and stuff but want to have all templates and everythign structured thanks to you first!

**Pull request merged**
