### PR TITLE
Add AwesomeChartJs

### PR DESCRIPTION
**Pull request by matriphe**
Added [AwesomeChartJs](http://cyberpython.github.io/AwesomeChartJS/) (Apache License v2.0) that support bar, pie, donut, and pareto.

I also updated README by adding pareto on create charts table section.

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
We're currently migrating the project to 3.0 version. All new libraries / types will still remain out as we're gonna use blade templating. The readme is 2.X so everything new is not yet added. I'm wondering why did your commit modify 224 files :o

**Comment by faustbrian** [comment]
This should be closed. He reverted all changes I made for views and the structure of the package.

**Comment by ConsoleTVs** [comment]
Just wait for @faustbrian to release the PR and for me to create a new version (3.0) and start adding things there!

**Comment by matriphe** [comment]
@ConsoleTVs OK! no problem! will keep tracking on this

**Pull request closed without merging**
