### PR TITLE
Add theme support for echarts

### PR DESCRIPTION
**Pull request by renardudezert**
Adding theme support for echarts. 
Possible values are : 'default', 'light','dark'
For example use `$chart->theme('light');` for setting the theme.

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
I can't accept this PR. First because modifying the base class is not ok (it's used by all charts libraries and not all support themes).

Second, you can find the ecahrts class specific trait here: https://github.com/ConsoleTVs/Charts/blob/master/src/Features/Echarts/Chart.php

And third, can you provide the documentation link where the theme stuff is located? I can't seem to find it

**Comment by ConsoleTVs** [comment]
Can you provide the documentation link where the theme stuff is located? I can't seem to find it

**Comment by renardudezert** [comment]
We can pass a theme in the init function : https://ecomfe.github.io/echarts-doc/public/en/api.html#echarts.init
The built-in theme are on the top-right corner on the samples page : https://ecomfe.github.io/echarts-examples/public/index.html

We can also download themes on the official echarts website : http://echarts.baidu.com/download-theme.html

**Comment by ConsoleTVs** [comment]
OK great one!

Now you need to removed all the things added in BaseChart and then add the definition of the $theme prop in the echarts class: https://github.com/ConsoleTVs/Charts/blob/master/src/Classes/Echarts/Chart.php

The rest seems great to go! Thanks!

**Comment by renardudezert** [comment]
Thanks !

I've just pushed the modifications.

**Comment by renardudezert** [comment]
@ConsoleTVs is it OK for you now ?

**Comment by ConsoleTVs** [comment]
It seems it's all alright! Great job @renardudezert !

I will release it now. I would love you to be the first to try it out, would it be possible for you to post here after you've tested it with the live version? If so, I'll update the docs with this new feature!

**Comment by ConsoleTVs** [comment]
Awesome job! Added to the docs beep boop beep! https://charts.erik.cat/customize_charts.html#echarts

**Pull request merged**
