### PR TITLE
Added new chart type areaspline for highcharts

### PR DESCRIPTION
**Pull request by hizbul25**
Hello,

I have added a new chart type [areaspline](http://www.highcharts.com/demo/areaspline) for highcharts.
Here is the example of using:

  ```
         $chart = Charts::multi('areaspline', 'highcharts')
			     ->title('My nice chart')
			     ->colors(['#ff0000', '#ffffff'])
			     ->labels(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday','Saturday', 'Sunday'])
			    ->dataset('John', [3, 4, 3, 5, 4, 10, 12])
			    ->dataset('Jane',  [1, 3, 4, 3, 3, 5, 4]);
			        
		return view('charts.testchart', ['chart' => $chart]); 
```

If you think it is useful then please accept my pull request.

- Hizbul Bahar
Dhaka, Bangladesh

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
What's the difference between the area and this?

**Comment by hizbul25** [comment]
In http://www.highcharts.com/demo/areaspline there is a **spline** , comparison point for each label.

**Comment by ConsoleTVs** [comment]
Very cool, but before I can merge the pull request you should update the official docs of the 3.0 version

They are located here: https://github.com/ConsoleTVs/Charts/blob/master/docs/3.0/readme.md

Simply modify the one from your forge adding everything the users need to know to use this one.

You'll pretty much need to add it to all the tables and mark it with a X on those who's available

At the moment you just added the "multi" chart. may you be able to add a "single" chart with this?

If so, make sure to add it as well and after your commits I'll merge it into the official! :D

**Comment by hizbul25** [comment]
Thanks, I'll do it.

**Comment by hizbul25** [comment]
@ConsoleTVs , i have added the user guide in docs, please have a look.

**Comment by ConsoleTVs** [comment]
Hi, it's the opposite, X means available, - means it's not.

**Comment by hizbul25** [comment]
sorry :p, changing

Best Regards...
Hizbul Bahar
Software Engineer, Dando, Dhaka
Cell: +8801918019179, +8801780338839

**Comment by ConsoleTVs** [comment]
Seems everything is correct now! Merging :p

**Pull request merged**
