### PR TITLE
Add method to set date and month format on Database

### PR DESCRIPTION
**Pull request by matriphe**
I need to manually set the date and month format, so I can use the format I want by setting using `setDateFormat()` and `setMonthFormat()` to set the format if `$fancy` set to true. 

I changed the `README.MD` by adding the functions.

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Looks very cool, make sure to pass StyleCI analysis next time! :D

**Comment by matriphe** [comment]
@ConsoleTVs thanks! I just realize, my PR didn't pass the StyleCI. I'm sorry!

**Comment by ConsoleTVs** [comment]
There's no problem! I'll always make sure they do before every release tho!, your methods were added in the 2.0.1 version! Thanks for the contribution! Any other ideas you might have you can always pull request or tell me! :D

**Comment by matriphe** [comment]
@ConsoleTVs thanks! you've done a great job here! 👍

**Comment by ConsoleTVs** [comment]
You're welcome! I've got a lot of things planned, not only for charts ofc

**Pull request merged**
