### PR TITLE
Remove unnecessary Use statement from MultiDatabase

### PR DESCRIPTION
**Pull request by jmowatt**
Fix the Database not found exception, both classes are in the same
namespace.

### CODE REVIEW

**Comment by jmowatt** [comment]
Fixes #129

**Comment by ConsoleTVs** [comment]
Thanks a lot!

**Comment by jmowatt** [comment]
@ConsoleTVs do you happen to have a plan of the next minor release that this fix will be in?

Thanks

**Comment by ConsoleTVs** [comment]
It's already up ;) on 4.0.5

**Pull request merged**
