### PR TITLE
Allow rendering of charts to custom element

### PR DESCRIPTION
**Pull request by Godofbrowser**
`{!! $chart->render('my-chart-container') !!}`

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Two things, imo you should reset the custom container after each render, and second make sure to pass styleCI analysis before any pull request!

Will look into it in few hours, could you explain me the usage of the _partials folder? I think it would be eaier to just set a parameter in the render that specifies the $chart->id to force it, nothing else, what do you think?

Also make sure all changes are written in the readme.md before any pull request!

As I said, I'll look into it later! Thanks!

**Comment by Godofbrowser** [comment]
Hello Erik, could you please explain what you mean by reseting the container? 

Also, the_partials folder is meant to hold the sub-templates: a part of the templates that hold the render element(in the case of $chart->render()), title and style... I noticed these portion of the templates are most times repeated so I thought it'll be good practice to include them when needed. 

Again, do you mean specifying a parameter in render like so `function render($id)`? 

Lastly, i will try update the Readme to reflect the changes. But will really appreciate if someone does too as I'm a little busy lately. Thanks.

**Comment by ConsoleTVs** [comment]
I'll be able to do it this weekend!

I mean, the parameter you pass the the render should not choose the partial you want, insead, should only set the ID of the chart (instead of random) because some people might want to use that variable later on o refer to the chart somehow. I mean it should not be a parameter because some libraries onyl work with certain types of containers, some only work with <divs>, others with <canvas> other with <svg> etc. allowing to choose witch one to use is not very usefull since probably will only work with the one they were created for.

**Comment by Godofbrowser** [comment]
okay, if i think i understand you better now.

But the parameter $customId is not meant for choosing which container the library will use.
It is for checking if the default container should be loaded or not.

for example `if( !$this->customId )` <=== if customId is not set

then,

`include __DIR__ . '/../_partials/div-container.php';` <== use default container

Also, in chart.php
`$this->id = $this->customId ? $this->customId : $this->randomString();` <== if $customId is not set, then use random. But if $customId is set, use $customId as $id

so after `$chart->render('my-div')` you can still call `echo $chart->id; //output: 'my-div'`

**Comment by ConsoleTVs** [comment]
so "my-div" only changes the $chart->id if I'm not wrong... in that case you dont need to check if it's set inside the view and u can replace the id

**Comment by Godofbrowser** [comment]
we need to check so that we don't provide additional container. see the screenshot below
sample chart page

**Comment by ConsoleTVs** [comment]
OHHH Now I understand what you want to do!!! :D As far as I see it, right now it's done correctly then! Good job!

**Comment by Godofbrowser** [comment]
Thanks Erik.

**Comment by bart** [comment]
When will you create a new release? I like to use this awesome feature because I don't want to render unneeded JS in the head section. Using dev-master is not the best idea for production. So please let me know, as soon as you release version 2.0.3. Awesome package!

**Comment by ConsoleTVs** [comment]
Hello @bart, The new version of Charts will be Charts 3.0, It will be released someday this week, after I finish exams (expect around wednesday), We'll document everything for the 3.0 as we have re-structured the directory schema as you might notice. Thanks for the interest! Keep an eye on the repository :)

**Comment by bart** [comment]
Hey @ConsoleTVs, that sounds pretty good! I'm really looking forward to it and I will try to help as much as I can. Will you release version 3 from the master branch? I tried it out last night and fell into some issues.

**Comment by ConsoleTVs** [comment]
Yes we will, I still have to test bunch of stuff first as people made lots of Pull Requests and I have to see what is going on first! What kind of issues did you run into?

**Comment by bart** [comment]
It's working without an error today, but I can't use the feature from above. The chart does not get rendered into the div.

```
<div id="area-types-pie-chart"></div>
```

...

```
@section('js')
    {!! $areaTypesPieChart->render('area-types-pie-chart') !!}
@endsection
```

**Comment by ConsoleTVs** [comment]
I'll see what i can do, but you don't need to render it to a specific container

**Comment by bart** [comment]
I know, but I want to render it to a specific container, because I don't want to load JS in the head section. Thanks!

**Comment by bart** [comment]
@ConsoleTVs Will take this into account for version 3? Tested dev-master and it doesn't work there.

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Charts/blob/master/src/Builder/Chart.php#L230

You mean this?

**Comment by bart** [comment]
Nope. I mean the content of this merged PR. I want to render the charts in my JS section instead of inside of the div itself.

**Comment by ConsoleTVs** [comment]
Oh.. atm it's not there.. will see if we can enable this. The fact is that i had to rewrite a lot of stuff because it was 95% broken. Literally, i had to loop over 100 files to fix them 1 by 1.

After 3.0 is released and stable, we can start adding things like this!

**Comment by bart** [comment]
Hmm that's bad. We can't use your library until this feature is inside :(

**Comment by ConsoleTVs** [comment]
Don't worry I'll see what i can do

**Comment by ConsoleTVs** [comment]
@bart Why is it so much important?

**Comment by bart** [comment]
It's important because we render all JS in the end of the body tag instead of the head section. And due to the performance we won't change this. But when using the current version, you always have to include the chart libraries in the head section to get it running. No Javascript above the fold ;)

**Comment by ConsoleTVs** [comment]
You know you can split the assets with the Charts::assets() function right?

```
Charts::assets(['google', 'chartjs', ...], 'styles'); //CSS
Charts::assets(['google', 'chartjs', ...], 'scripts'); //JS
```

**Comment by bart** [comment]
Yes, but calling ``` $chart->render()``` will generate JS that needs some JS classes that are not available there because we load them later.

**Comment by ConsoleTVs** [comment]
I understand you issue, Will look into it

**Comment by bart** [comment]
Thanks @ConsoleTVs

**Comment by ConsoleTVs** [comment]
@bart Added here https://github.com/ConsoleTVs/Charts/commit/dac1643449261116f7c44822d3df822097da8d0f

https://github.com/ConsoleTVs/Charts/blob/dac1643449261116f7c44822d3df822097da8d0f/src/Builder/Chart.php#L74

**Comment by bart** [comment]
Whaaat??? I will check this out as quick as possible! Thank you so much @ConsoleTVs

**Comment by ConsoleTVs** [comment]
Basically it changes the chart id to the specified one, so it will render in a div called in the container method, if this string is set, the charts won't echo any division so they will render to the div you've manually created with an ID of the string passed in the contaienr method (a bit messy after all haha)

**Comment by bart** [comment]
There is a small issue in your method. You are passing $division but assigning the variable $container. I've created pull request #81 that fixes it. After this fix it works great. If you use this feature, you only have to keep in mind not using hyphens as container name because this results in a JS error. Last but not: Awesome work. Thank you so much @ConsoleTVs Can't wait for the next stable release.

**Comment by ConsoleTVs** [comment]
You're welcome! Willing to keep adding more things at charts! Thanks for the typo error, sometimes I'm making too many things at the same time haha :D

Gonna create the release today since everything seems documented and correctly done

**Pull request merged**
