### PR TITLE
Cleanup project

### PR DESCRIPTION
**Pull request by faustbrian**
I just started to cleanup the project a bit which includes things like using Laravel methods to keep the code clean and maintainable, render views with Blade and such.

**Changes:**	
- Use Laravel helpers
- Remove dirty includes.php *(Really bad practice)*
- Use Blade for views
- Move templates to views
- Add laravelcollective/html dependency *(This will be needed in my next PR)*
- Make a proper facade
- Add .editorconfig
- Add .styleci.yml
- Load and publish views
- Move Chart Builder
- Move assets directory
- Move assets to config

I will be sending another PR within the next few days after this has been merged which will update all views to use the Blade Syntax rather than pure PHP as the templates are a mess at the moment. I was almost done with updating the templates to blade when a big PR got merged and most of my changes were lost.

**Please note that no new release should be tagged after merging this as there will come another PR for the views.**

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Wow that's some big steps over here, thanks a lot, honestly! I'm curious on how would you use the forms for the dependency?

**Comment by faustbrian** [comment]
The `laravelcollective/html` will mostly be used to generate style and script tags to make the code cleaner since we then can just do things like `HTML::style($file); // $file could be config('chart.assets.highchartsjs.styles.main')` instead of cluttering the code with raw HTML and PHP.

**Comment by ConsoleTVs** [comment]
Wow, I really have no words for all the help you guys are giving me... You can take all of your time, nothing is in a hurry! Your idea is very clever as well and I think that it will look very cool. What type of versioning do you want to keep? since you changed the directory structure now people will need to change the alias to the new one (you already documented it, and that's good) but people need to realize about that change, don't you think?

**Comment by faustbrian** [comment]
I think when I've done all the changes we should jump to version 3.0.0 since it has major changes and most likely won't be backwards-compatible. If needed I can add a migration guide from 2.0.0 to 3.0.0.

**Comment by ConsoleTVs** [comment]
Yeah sure, if you have time to. What do you think about creating a simple docs page? seems the .md is getting pretty big... I think it's something I should consider :D

**Comment by faustbrian** [comment]
Yeah the README is getting somewhat big, you could either create a docs directory and put multiple markdown files in there or create a gh-pages branch if you would want to have a page with a design.

**Comment by ConsoleTVs** [comment]
Indeed, will take a look into it!

**Comment by ConsoleTVs** [comment]
One last thing, make sure to pass StyleCI analysis next time, since this pull request was not passing it!

**Comment by faustbrian** [comment]
No problem, from now on different styles will be applied anyways.

**Pull request merged**
