### PR TITLE
feat(api): Adds a refresh() method

### PR DESCRIPTION
**Pull request by sardoj**
This pull request adds a simple way to refresh data in an api chart.
(See: https://charts.erik.cat/api_charts.html#building-the-chart)

Now a `chartId_api_url` variable and a `chartId_refresh()` function are available.

It is possible to do, for example:
```js
gpsjedrixcobvnumklwqztfha_api_url = "http://mysite.com/get_data?date_start=2018-01-01&date_start=2019-12-31";
gpsjedrixcobvnumklwqztfha_refresh();
```

So it is easy to reload data in all charts after selecting a date, or applying a filter.

See: https://charts.erik.cat/render_charts.html#sample-html

### CODE REVIEW

**Comment by sardoj** [comment]
It would be great to display a loader when refreshing.
The current library's code removes the loader from DOM after creating a chart (for example: https://github.com/ConsoleTVs/Charts/blob/master/src/Views/chartjs/script.blade.php#L11)

**Comment by ConsoleTVs** [comment]
That is a very interesting PR. I am very happy! I agree on the loader. What solutions do you find best?

**Comment by sardoj** [comment]
Thank you!
For the loader maybe you can hide it instead to remove it from the DOM. But with the  actual style it is displayed below the chart. Could you adapt the CSS of the loader please?
And we can add a line into the refresh method for toggling the loader.

**Comment by ConsoleTVs** [comment]
While I look into those things (I have few / no time) I don't want to miss this cool update. So I would love to merge it. Would you consider some words on how to use it?

I would love if you can add your own words to the official docs: https://github.com/ConsoleTVs/ChartsDocs/blob/master/docs/api_charts.md

Just make a PR there with some description / usage / example. When this is done, I will push both repos and make a new release 😄

**Comment by sardoj** [comment]
I found a way to display loader ;-)
And now you can pass the new `api_url` in the refresh() method!
I will update the doc.

**Comment by ConsoleTVs** [comment]
Oh, that's fantastic, I assume it's all done then! Release incomming!

**Comment by ConsoleTVs** [comment]
Just letting you know that I've updated the docs, and released a new version.

Congratulations, your feature is added in the 100th release 😄 

I've also added a reference to your github profile on the docs. If you dislike that, just let me know.

Thanks for the effort @sardoj !

**Comment by sardoj** [comment]
Thank you! 
I was very happy to collaborate on your great project!

**Pull request merged**
