### PR TITLE
Fix issue with IE11 not supporting .remove();

### PR DESCRIPTION
**Pull request by SDekkers**
This PR is to resolve issues with IE11 not supporting .remove()

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Chartjs is not the only library behind a loader....

**Comment by SDekkers** [comment]
I've included fixes for all 4 now.

**Comment by ConsoleTVs** [comment]
Seems good :)

**Comment by ConsoleTVs** [comment]
Thanks a lot!

**Pull request merged**
