### PR TITLE
Added Horizontal Bar to Chart.js

### PR DESCRIPTION
**Pull request by ThomasMountain**
Add Horizontal Bar to Chart.js
Add Multi Horizontal Bar to Chart.js

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Nice one!

**Comment by BlueTeck** [comment]
Nice :)

Maybe they should be added to the readme?

**Comment by ConsoleTVs** [comment]
Indeed, make sure to document changes when making a pull request, so things don't get tricky later on

**Comment by ConsoleTVs** [comment]
Removed with 3.0 since they were not acting correctly (probably chartjs bug or something) changed the type to bar and it worked, so meanwhile I'll delete them, I might consider reading them in a future as it's something cool, sorry!

**Pull request merged**
