### PR TITLE
Add Label Option for Chartjs

### PR DESCRIPTION
**Pull request by zack6849**

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
This class is meant not to be modified. You should probably look here:

https://github.com/ConsoleTVs/Charts/tree/master/src/Features/Chartjs

Also, the labels are something specific to a chart, not a dataset. there can be N datasets but the chart may only contain a single X labels

**Comment by ConsoleTVs** [comment]
As a side note, all charts supports labels by default:

https://github.com/ConsoleTVs/Charts/blob/master/src/Classes/BaseChart.php#L167

So I don't know what is your intention in here

**Comment by zack6849** [comment]
I'm confused, Chartjs says a dataset can have a label?

https://www.chartjs.org/docs/latest/charts/bar.html#general

See: label

I was having troubles using this library with a bar chart, I noticed you had "traits" for the things that the library supported like background colors per dataset, so I thought this would be helpful.

Re: my intention, honestly im just trying to use this for bar charts and pie charts, it seemed to get close to what I wanted, but not quite.

Is there any one library you'd suggest people go with? 
Your documentation is helpful, but somewhat sparse when it comes to different chart types

**Comment by ConsoleTVs** [comment]
Can you post an issue with a feature request for the per-bar preset? Thanks!

Regarding to the label you're right, I confused label for labels. Label is per-dataset, that's correct.

Therefore, your PR is valid. Thanks a lot for the contribution!

I normally go with chartjs or echarts as a personal preference.

The docs don't go into deep details on the charts because it's mostly not it's responsibility, each fronted have different charts / variants / etc.

**Pull request merged**
