### PR TITLE
Implemented label overriding feature for database groupBy() method

### LINKED ISSUE #82: [Feature request] Override labels
Maybe it would be great to override labels on the fly either by setting them directly as an associative array or by passing data as collection instead of a eloquent object.

Example:

```
$chart = Charts::database(Account::all(), 'pie', 'highcharts')
            ->title(__('Account types'))
            ->dimensions(1000, 500)
            ->responsive(true)
            ->groupBy('type');
``` 

In this case, type is an integer where 1 stands for admin account, 2 stands for user account and 3 stands for guest account. I expect the chart to show me a pie diagram with the labels "Admin", "User" and "Guests" instead of 1, 2 and 3.

Maybe something like this?

```
$chart = Charts::database(Account::all(), 'pie', 'highcharts')
            ->title(__('Account types'))
            ->dimensions(1000, 500)
            ->responsive(true)
            ->labels([1 => 'Admin', 2 => 'User', 3 => 'Guests'])
            ->groupBy('type');
```

What do you think about it? Would it makes sense?

### PR DESCRIPTION
**Pull request by bart**
Fixes #82

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
This give me conflips upon this: https://github.com/ConsoleTVs/Charts/pull/83

What do you think it's best to use?

**Comment by bart** [comment]
It's always good to pass a closure but in most cases simply passing a field would be enough and the most easy solution. I would make it optional, like in most Laravel methods. Maybe you can check if the first parameter is a closure ( is_callable() ) and if so, call it. Otherwise continue as before.

What do you think?

**Comment by ConsoleTVs** [comment]
Okai, will see how it goes :D

**Comment by bart** [comment]
Thanks for merging and releasing!

**Comment by ConsoleTVs** [comment]
You're welcome!

**Pull request merged**
