### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by SDekkers**
Proper Laravel 6.0 support

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Isn't `^X.0` the same as `X.*` ?

I would argue that if I needed 6.1 or above, your solution would be better.

Does it have any improvement or issue?

**Comment by SDekkers** [comment]
Laravel itself suggest to use ^6.0 when requiring any of their packages

**Comment by ConsoleTVs** [comment]
Great then, I would suggest to change it for 5.X as well. May you push a new commit before I merge?

**Comment by SDekkers** [comment]
Done that.

**Comment by ConsoleTVs** [comment]
Thanks for the addition!

**Pull request merged**
