### PR TITLE
Refactoring Database.php

### PR DESCRIPTION
**Pull request by Big-Shark**

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
This is something I was wishing to do few months later. Seems cool. Does it do exactly the same?

**Comment by Big-Shark** [comment]
@ConsoleTVs yes, I checked and all good

**Comment by Big-Shark** [comment]
@ConsoleTVs U can check this again, and if all good, will merge it

**Comment by ConsoleTVs** [comment]
Good to merge, thanks a lot!

**Pull request merged**
