### PR TITLE
Added DB counted procecssing

### PR DESCRIPTION
**Pull request by oceanapplications**
Example:
     $productData = $product->orders()->select('orders.created_at', DB::raw('count(orders.id) as count'))->groupBy(DB::raw('Date(orders.created_at)'))->get();
     $productData = Charts::database($productData)->lastByDay(7, false, true);

Set precounted to true and pass database results with a count field to create a chart from DB counted data.  Much faster processing than processing in PHP.

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Could you explain this in depth? What is it suposed to do?

**Comment by oceanapplications** [comment]
Instead of running a query like `Orders::all();` and passing the result to the chart creation then relying on php to group and count the data by date, you can do something like `Orders::select('orders.created_at', DB::raw('count(orders.id) as count'))->groupBy(DB::raw('Date(orders.created_at)'))->get();` which does the counting and grouping in the database.  

With a database of 21k records, selecting all the rows then processing in php was taking over 30 seconds and timing out while processing it in the database completes in 60ms.

My implementation might not be perfect but it was simple to do.

**Comment by ConsoleTVs** [comment]
OK, i think it's a good idea, but requires something diferent.

To merge this PR you'll need:

- Create a new method & attribute in the Database.php chart and call it something like: ```->precount(true/false)```
- Modify the existing functions to use this feature acordingly if set to true. It should default to false.
- Modify the 3.0 readme with this information

If this is done I'll be happy to merge it :)

Example usage:

```
$productData = $product->orders()->select('orders.created_at', DB::raw('count(orders.id) as count'))->groupBy(DB::raw('Date(orders.created_at)'))->get();
$productDataChart = Charts::database($productData)->precount(true)->lastByDay(7, false);
```

**Comment by ConsoleTVs** [comment]
Nice one!, merge on the way!

**Comment by ConsoleTVs** [comment]
Available here: https://github.com/ConsoleTVs/Charts/releases/tag/3.0.7

**Comment by leonh12** [comment]
How can I get a chart with i.e. AVG(SALARY). I just want one bar chart. @ConsoleTVs @oceanapplications

**Comment by ConsoleTVs** [comment]
If you have a lot of data in your db like this pull request suggests, use this method. Otherwise, use the standard method to generate a simple array.

Get each month's data, make a simple average and save it into an array like this:

[10, 15, 8, 11] (sample average array) or 4 months

then set the labels for this data: ["March", "April", "May", "June"]

And create a normal chart using the "create" method of charts:

```
Charts::create('bar', 'highcharts')
    ->title('Average Bar Chart')
    ->labels(["March", "April", "May", "June"])
    ->values([10, 15, 8, 11])
    ->dimensions(1000,500)
    ->responsive(false);
```

**Pull request merged**
