### PR TITLE
add option to load jquery in config

### PR DESCRIPTION
**Pull request by Godofbrowser**
Useful if jQuery is already loaded in the app

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Hi! Seems like just few minutes ago https://github.com/ConsoleTVs/Charts/pull/36 was created and changed the way jquery works, still haven't accepted any since I'm awaiting for his response but his pull request allowed to choose it as optional as well!

Will keep this alive meanwhile

**Comment by Godofbrowser** [comment]
I think #36 only added ability to choose assets by type (css or js).. the option whether or not to load jquery isn't there. I'm waiting for your actions so i can add ability to call $chart->render('custom-element')

**Comment by ConsoleTVs** [comment]
Hello, I'll merge the #36 and close this one, since he already filters this! Your new feature inside the render method seems cool, will this replace the chart id? I'll wait for it!

**Comment by Godofbrowser** [comment]
Hi, the filter is cool. As for rendering to a custom element, I've began work on it. I've created a new folder inside the templates directory called "_partials". Aimed at preventing some code repetitions.

**Comment by ConsoleTVs** [comment]
Hmmm what would you do inside this folder?

**Pull request closed without merging**
